### ISSUE TITLE
Not working anymore since last update of Core and lastest update of HA v14

### ISSUE THREAD

**Issue by freeman59** [Patrick762/hacs-streamdeck#5] opened 2024-12-10 18:17 UTC
Hello

I've just perform an update to the lastest HA version 14 and the HA Core 2024.12.1

Since the update, the Streamdeck is not working anymore.

I've rolled back and can get it works again. So I tried to restart the update but same problem. Seems the problem came from HA 14 (not the Core). 

I can see this notification : 

The following integrations and platforms could not be set up:

[streamdeck](https://github.com/Patrick762/hassio-streamdeck) ([Show logs](https://wwwww.wwww.fr/config/logs?filter=streamdeck))

where wwwww.wwww is my HA url.

Thanks for your help

**Comment by gibokun** [comment] 2024-12-10 18:29
Same error here. Some times is more helpfull to add the logs or  screenshots. :D 

Detalles de registro (ERROR)
Registrador: homeassistant.setup
Fuente: setup.py:269
Ocurrió por primera vez: 11:20:10 (1 ocurrencias)
Última vez registrado: 11:20:10

Setup failed for custom integration 'streamdeck': Requirements for streamdeck not found: ['streamdeckapi==0.0.11'].

::::::::::::::::::::::::::::::::::::::::::::::::::

Registrador: homeassistant.util.package
Fuente: util/package.py:152
Ocurrió por primera vez: 11:20:01 (3 ocurrencias)
Última vez registrado: 11:20:10

Unable to install package streamdeckapi==0.0.11: × No solution found when resolving dependencies: ╰─▶ Because streamdeckapi==0.0.11 depends on websockets==11.0.2 and websockets>=13.1, we can conclude that streamdeckapi==0.0.11 cannot be used. And because you require streamdeckapi==0.0.11, we can conclude that your requirements are unsatisfiable.

**Comment by Patrick762** [comment] 2024-12-21 19:46
Root cause: https://github.com/Patrick762/streamdeckapi
I'll have to look into this a bit deeper, because there was a problem with the websockets if I remember correctly.

I also added a docker image now.
WIP Pull request: https://github.com/Patrick762/streamdeckapi/pull/11

**Comment by Patrick762** [comment] 2024-12-21 21:36
@freeman59 @gibokun
Integration should work again with version 0.0.8.
I didn't do any updates since I didn't know there was someone using it (this integration was part of my bachelor thesis). Maybe I should fix some of the bugs over the holidays

**Comment by gibokun** [comment] 2024-12-22 02:07
Thanks @Patrick762 ! Updating it now! The weird thing was that it was complaining on HA, but the buttons on streamdeck were still working fine :D

**Comment by gibokun** [comment] 2024-12-22 02:31
<img width="235" alt="image" src="https://github.com/user-attachments/assets/a11698bc-9695-4987-a99d-b2ca523ce266" />
Working fine again! thanks!

**Comment by Patrick762** [comment] 2024-12-22 10:24
Maybe I should include an overview on how the system works.
Are you using the plugin or the python server?

**Comment by gibokun** [comment] 2024-12-22 12:03
The pluging
<img width="358" alt="image" src="https://github.com/user-attachments/assets/7ef0359f-4ef2-4cc0-a0c6-db6856f5577e" />

**Closed as completed** 2024-12-29 20:44 UTC
Labels: bug
